[build]
  # Directory where Netlify should look for the functions
  functions = "netlify/functions"
  # Directory where your site is built. Since you're using serverless functions only, you can set this to an empty directory.
  publish = "."

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  # Customize the default settings for your functions
  node_bundler = "esbuild" # You can use esbuild or another bundler like "zisi"
  external_node_modules = ["puppeteer-extra", "puppeteer-core", "axios", "cheerio"]

  # Specifies the timeout for the function execution
  timeout = 120 # Maximum execution time in seconds

[functions."coffee-api"]
  # Adjust memory limit for this function
  memory = 1024 # Set memory in MB (1 GB here)
  included_files = ["path/to/chrome.exe"] # Specify if you have other necessary files

[dev]
  # Setup Netlify Dev to use when testing locally
  functions = "netlify/functions"
  publish = "."
